version: "3.9"

services:
  mysql:
    image: mysql:5.6.51
    container_name: mysql
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbt
      - MYSQL_PASSWORD=dbt
  mongo:
    image: mongo:4.2.12-bionic
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
  dremio:
    image: dremio/dremio-oss:12.1.0
    container_name: dremio
    restart: on-failure
    ports:
      - 9047:9047
      - 31010:31010
      - 45678:45678
  # dbt:
  #   build:
  #     context: .
  #   container_name: dbt
  #   restart: on-failure
  #   command: poetry run dbt debug --project-dir=demo_dbt_dremio --profiles-dir=demo_dbt_dremio
  #   depends_on:
  #     - dremio
