name: 'demo_dbt_dremio'
version: '1.0.0'
config-version: 2

profile: 'demo_dbt_dremio'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  demo_dbt_dremio:
      example:
          materialized: table
