demo_dbt_dremio:
  target: prod
  outputs:
    prod:
      type: dremio
      threads: 2
      driver: /opt/dremio-odbc/lib64/libdrillodbc_sb64.so
      host: 0.0.0.0
      port: 31010
      environment: env_dbt
      schema: FS
      user: dbt
      password: DEMO_DBT_DREMIO_1
