demo_dbt_dremio:
  outputs:
    prod:
      type: dremio
      threads: 2
# please replace driver below with the one you gave to your dremio odbc driver installation
      driver: /opt/dremio-odbc/lib64/libdrillodbc_sb64.so
      host: dremio
      port: 31010
      environment: env_dbt
      schema: FS
      user: dbt
      password: DEMO_DBT_DREMIO_1
  target: prod
