version: 2

models:
    - name: aggregated_transactions
      description: "All aggregated transactions sorted from highest to lowest"
      columns:
          - name: name
            description: "User name"
          - name: total_spent
            description: "How much money user has spent"
